import logging

APP_HOST="127.0.0.1"
APP_PORT="8888"

AWS_ACCESS_KEY=""
AWS_BUCKET_NAME=""
AWS_BUCKET_REGION=""
AWS_SECRET_ACCESS=""

AUTH_HEADER_VAL=""

LOCAL_STORAGE_DIR="tempstore"

THREAD_WORKERS=4
NUMBER_OF_FORKS=1

MB = 1024 * 1024
GB = 1024 * MB
TB = 1024 * GB

MAX_BUFFER_SIZE = 4 * MB
MAX_BODY_SIZE = 4 * MB
MAX_STREAMED_SIZE = 1 * TB

SIGNED_URL_EXPIRATION=60

MONGODB_USER = ""
MONGODB_PASS = ""
MONGODB_NAME = "filedetails"
MONGODB_HOST = "127.0.0.1:27017"

try:
    from local_settings import *
except:
    logging.warning("No local settings found")
